### ISSUE TITLE
Bump metalsmith-metallic version

### ISSUE THREAD

**Issue by weswigham** [cameronroe/metalpress#12]
Hi there, I've noticed you depended on `metalsmith-metallic`. I've recently bumped the version to (and published) `1.0.0` with [PR 8](https://github.com/weswigham/metalsmith-metallic/pull/8), as I felt the bugfix was semver-major, as it impacts consumers of the metalsmith chain I emit. I just wanted to let you know, in case updating it impacts your code in the future.

**Comment by cameronroe** [comment]
Thanks, I'll keep that in mind.
